# Site settings
title: 지식 기록하는 블로그
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sihong12.github.io"

# User settings
username: Sihong Park :)
user_description: Web Developer
user_title: Web Developer
email: pozt1234@gmail.com
#twitter_username: lorem_ipsum
github_username: Sihong12
#gplus_username:  lorem_ipsum
disqus_username: https-sihong12-github-io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Programming
    url: /programming
    sublink: true
  - title: Database
    url: /database
    sublink: true
  - title: Web
    url: /web
    sublink: true
  - title: TIL
    url: /til
    sublink: true
  - title: 알고리즘
    url: /algorithm
    sublink: true
  - title: Tags
    url: /tags
  - title: Archive
    url: /archive
  - title: About me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
